/* 
 * SQL script for creating database tables 
 */
/**
 * Author:  AJC
 */

CREATE TABLE JUDETE (
COD_JUDET SMALLINT NOT NULL, 
DENUMIRE VARCHAR(25) NOT NULL, 
PRIMARY KEY (COD_JUDET)
);

CREATE TABLE LOCALITATI (
COD_LOCALITATE SMALLINT NOT NULL, 
DENUMIRE VARCHAR(25) NOT NULL, 
COD_JUDET SMALLINT NOT NULL, 
PRIMARY KEY (COD_LOCALITATE)
);

CREATE TABLE PERSOANE (
CNP VARCHAR(13) NOT NULL,
NUME VARCHAR(25) NOT NULL, 
PRENUME VARCHAR(25) NOT NULL, 
VARSTA SMALLINT NOT NULL, 
DOMICILIU VARCHAR(25) NOT NULL, 
COD_LOCALITATE SMALLINT NOT NULL, 
PRIMARY KEY (CNP)
);

--Insert data in table JUDETE
INSERT INTO TEST.JUDETE (COD_JUDET, DENUMIRE) 
	VALUES (1, 'ILFOV');
INSERT INTO TEST.JUDETE (COD_JUDET, DENUMIRE) 
	VALUES (2, 'PRAHOVA');
INSERT INTO TEST.JUDETE (COD_JUDET, DENUMIRE) 
	VALUES (3, 'CLUJ');
INSERT INTO TEST.JUDETE (COD_JUDET, DENUMIRE) 
	VALUES (4, 'ALBA');

--Insert data in table LOCALITATI
INSERT INTO TEST.LOCALITATI (COD_LOCALITATE, DENUMIRE, COD_JUDET) 
	VALUES (1, 'BUCURESTI', 1);
INSERT INTO TEST.LOCALITATI (COD_LOCALITATE, DENUMIRE, COD_JUDET) 
	VALUES (2, 'PLOIESTI', 2);
INSERT INTO TEST.LOCALITATI (COD_LOCALITATE, DENUMIRE, COD_JUDET) 
	VALUES (3, 'CLUJ NAPOCA', 3);
INSERT INTO TEST.LOCALITATI (COD_LOCALITATE, DENUMIRE, COD_JUDET) 
	VALUES (4, 'ALBA IULIA', 4);

--Insert data in table PERSOANE
INSERT INTO TEST.PERSOANE (CNP, NUME, PRENUME, VARSTA, DOMICILIU, COD_LOCALITATE) 
	VALUES ('1680507121213', 'ION', 'ION', 20, 'STRADA LUMINII, 23', 1);
INSERT INTO TEST.PERSOANE (CNP, NUME, PRENUME, VARSTA, DOMICILIU, COD_LOCALITATE) 
	VALUES ('2670203112234', 'PETRE', 'MARIA', 22, 'STRADA PRINCIPALA', 3);
INSERT INTO TEST.PERSOANE (CNP, NUME, PRENUME, VARSTA, DOMICILIU, COD_LOCALITATE) 
	VALUES ('1031212123458', 'PETRE', 'PETRE', 28, 'STRADA CAMPULUI, 3', 2);
INSERT INTO TEST.PERSOANE (CNP, NUME, PRENUME, VARSTA, DOMICILIU, COD_LOCALITATE) 
	VALUES ('2990101232345', 'ION', 'ELENA', 18, 'STRADA CAMPULUI, 3', 4);
